INHack20\ControlDistribucionBundle\Entity\Caso:
  properties:
    nroAsuntoFiscal:
      - NotBlank: { message: Ingrese el N° Causa }
    nroOficioFiscal:
      - NotBlank: { message: Ingrese el N° Oficio }
    nombreImputado:
      - NotBlank: { message: Ingrese el nombre del imputado }
    nombreVictima:
      - NotBlank: { message: Ingrese el nombre de la victima }
    pieza:
      - NotBlank: { message: Ingrese la cantidad de piezas }
      - Type:
         type: integer
         message: Debe ingresar un numero entero

INHack20\ControlDistribucionBundle\Entity\Causa:
  properties:
    nombre:
      - NotBlank: { message: Debe ingresar el nombre de la causa }
    tribunalTipo:
      - NotNull: { message: Debe selecionar el tipo de tribunal }
      
INHack20\ControlDistribucionBundle\Entity\Estado:
  properties:
    nombre:
      - NotBlank: { message: Debe ingresar el nombre del estado }

INHack20\ControlDistribucionBundle\Entity\Fiscalia:
  properties:
    nombre:
      - NotBlank: { message: Debe ingresar el nombre de la fiscalia }
    estado:
      - NotNull: { message: Debe seleccionar el estado de la fiscalia }

INHack20\ControlDistribucionBundle\Entity\Grupo:
  properties:
    nombre:
      - NotBlank: { message: Debe ingresar el nombre del grupo }
      
INHack20\ControlDistribucionBundle\Entity\Horario:
  properties:
    dias:
      - NotBlank: { message: Debe ingresar los dias correspondientes a este horario }
    horaInicio:
      - NotBlank: { message: Seleccione la hora de entrada }
    horaFin:
      - NotBlank: { message: Seleccione la hora de salida }
      
INHack20\ControlDistribucionBundle\Entity\Tribunal:
  properties:
    nro:
      - NotBlank: { message: Debe ingresar el numero del tribunal }
      - Type:
          type: integer
          message: Debe ingresar un numero entero
    tribunalTipo:
      - NotNull: { message: Debe seleccionar el tipo de tribunal }
    grupo:
      - NotNull: { message: Debe seleccionar el grupo de horario perteneciente }

INHack20\ControlDistribucionBundle\Entity\TribunalTipo:
  properties:
    nombre:
      - NotNull: { message: Debe ingresar el nombre del tribunal }
    limiteCausas:
      - NotNull: { message: Debe ingresar el limite de causas }