security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_USER:  ROLE_USER
        ROLE_ADMIN:       [ROLE_USER,ROLE_SUPER_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_SUPER_USER,ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            #anonymous: true
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /login
    
    firewalls:
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /login
            anonymous: ~
            
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        - { path: ^/profile/edit, role: ROLE_SUPER_ADMIN }
        #Permiso para acceder a ruta que devuelve json
        - { path: ^/configuracion/fiscalia/\d+/listaFiscalias, role: ROLE_USER }
        - { path: ^/configuracion/, role: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }        
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
