parameters:
    #Version de la aplicacion
    VERSION_APP : 1.0.0
    #Limite de paginacion
    LIMITE_PAGINACION : 3
    #Estado de registro y actualizacion
    FALLO_REGISTRO: 1
    EXITO_REGISTRO: 6
    EXITO_ACTUALIZACION: 2
    FALLO_ACTUALIZACION: 3
    EXITO_ELIMINACION: 7
    # Errores de Distribucion
    TRIBUNAL_NO_DISPONIBLE: 4
    INHIBICION_NO_PERMITIDA: 5