<?php

namespace INHack20\ControlDistribucionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DistribucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistribucionRepository extends EntityRepository
{
    public function findDistribucionesHoy($tribunalTipo){
        $fechaHoy = new \DateTime('today');
        $qb = $this->getEntityManager()
                ->createQueryBuilder();
        $qb->select('d')
                ->addSelect($qb->expr()->count('d.tribunal'))
                ->from('INHack20ControlDistribucionBundle:Distribucion', 'd')
                ->join('d.tribunal', 't')
                ->where('t.tribunalTipo= :tribunaltipo')
                ->andWhere($qb->expr()->like('d.creado',"'".$fechaHoy->format('Y-m-d')."%'"))
                ->andWhere('t.despacho = true')
                ->groupBy('d.tribunal')
                ;
        $qb->setParameter('tribunaltipo', $tribunalTipo);
        //echo $qb->getDQL();
        //die;
        $query = $qb->getQuery()->getResult();
        return $query;
    }
}